services:
  storage:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: storage
    environment:
      - STORAGE_PORT=5555
      - STORAGE_HOST=0.0.0.0
      - MODFILE=/server/mods.json
      - DB_PATH=/server/db.json
    volumes:
      - ./mods.json:/server/mods.json
      - ./db.json:/server/db.json

  backend:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: backend
    environment:
      - GAME_PORT=21025
      - GAME_HOST=0.0.0.0
      - CLI_PORT=21026,
      - CLI_HOST=localhost
      - STORAGE_PORT=5555
      - STORAGE_HOST=storage
      - MODFILE=/server/mods.json
      - ASSET_DIR=assets
      - SERVER_PASSWORD=
      - STEAM_KEY=
    restart: always
    depends_on:
      - storage
    volumes:
      - ./mods.json:/server/mods.json

  main:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: main
    environment:
      - STORAGE_PORT=5555
      - STORAGE_HOST=storage
      - MODFILE=/server/mods.json
    restart: always
    depends_on:
      - storage
    volumes:
      - ./mods.json:/server/mods.json

  runner:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: runner
    environment:
      - STORAGE_PORT=5555
      - STORAGE_HOST=storage
      - MODFILE=/server/mods.json
      - RUNNER_THREADS=4
    restart: always
    depends_on:
      - storage
    volumes:
      - ./mods.json:/server/mods.json