export enum EventCode {
    EVENT_ATTACK = 1,
    EVENT_OBJECT_DESTROYED = 2,
    EVENT_ATTACK_CONTROLLER = 3,
    EVENT_BUILD = 4,
    EVENT_HARVEST = 5,
    EVENT_HEAL = 6,
    EVENT_REPAIR = 7,
    EVENT_RESERVE_CONTROLLER = 8,
    EVENT_UPGRADE_CONTROLLER = 9,
    EVENT_EXIT = 10,
    EVENT_POWER = 11,
    EVENT_TRANSFER = 12,
};