export enum EventAttackType {
    EVENT_ATTACK_TYPE_MELEE = 1,
    EVENT_ATTACK_TYPE_RANGED = 2,
    EVENT_ATTACK_TYPE_RANGED_MASS = 3,
    EVENT_ATTACK_TYPE_DISMANTLE = 4,
    EVENT_ATTACK_TYPE_HIT_BACK = 5,
    EVENT_ATTACK_TYPE_NUKE = 6,
};